name: ci
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ```
            ${{ secrets.JINGMING_FAKE_SECRET }}
            ```
